In [ ]:
!wget https://drive.google.com/uc?id=1LL6moSzpUVxJUTMeXihWvUxBJNjvj6EH -O sample_submission.csv
!wget https://drive.google.com/uc?id=1Ui2t87X3in-Wu-pnjkDXa_VtPsVafi0l -O test.csv
!wget https://drive.google.com/uc?id=159PZX3X5rpUO-WbzWyC9whnc8B4mNqJl -O train.csv

--2026-05-13 20:37:44--  https://drive.google.com/uc?id=1LL6moSzpUVxJUTMeXihWvUxBJNjvj6EH
Resolving drive.google.com (drive.google.com)... 142.251.163.102, 142.251.163.113, 142.251.163.100, ...
Connecting to drive.google.com (drive.google.com)|142.251.163.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1LL6moSzpUVxJUTMeXihWvUxBJNjvj6EH [following]
--2026-05-13 20:37:44--  https://drive.usercontent.google.com/download?id=1LL6moSzpUVxJUTMeXihWvUxBJNjvj6EH
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.179.132, 2607:f8b0:4004:c1f::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.179.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15354 (15K) [application/octet-stream]
Saving to: ‘sample_submission.csv’

sample_submission.c 100%[===================>]  14.99K  --.-KB/s    in 0s

2026-05-13 20:37:45 (78.3 MB/s) - ‘sample_submission.csv’ saved [15354/15354]

--2026-05-13 20:37:45--  https://drive.google.com/uc?id=1Ui2t87X3in-Wu-pnjkDXa_VtPsVafi0l
Resolving drive.google.com (drive.google.com)... 142.251.163.102, 142.251.163.113, 142.251.163.100, ...
Connecting to drive.google.com (drive.google.com)|142.251.163.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1Ui2t87X3in-Wu-pnjkDXa_VtPsVafi0l [following]
--2026-05-13 20:37:45--  https://drive.usercontent.google.com/download?id=1Ui2t87X3in-Wu-pnjkDXa_VtPsVafi0l
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.179.132, 2607:f8b0:4004:c1f::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.179.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 440872 (431K) [application/octet-stream]
Saving to: ‘test.csv’

test.csv            100%[===================>] 430.54K  --.-KB/s    in 0.02s

2026-05-13 20:37:46 (18.6 MB/s) - ‘test.csv’ saved [440872/440872]

--2026-05-13 20:37:46--  https://drive.google.com/uc?id=159PZX3X5rpUO-WbzWyC9whnc8B4mNqJl
Resolving drive.google.com (drive.google.com)... 142.251.163.102, 142.251.163.113, 142.251.163.100, ...
Connecting to drive.google.com (drive.google.com)|142.251.163.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=159PZX3X5rpUO-WbzWyC9whnc8B4mNqJl [following]
--2026-05-13 20:37:46--  https://drive.usercontent.google.com/download?id=159PZX3X5rpUO-WbzWyC9whnc8B4mNqJl
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.179.132, 2607:f8b0:4004:c1f::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.179.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1359909 (1.3M) [application/octet-stream]
Saving to: ‘train.csv’

train.csv           100%[===================>]   1.30M  --.-KB/s    in 0.09s

2026-05-13 20:37:47 (14.1 MB/s) - ‘train.csv’ saved [1359909/1359909]

In [17]:
import pandas as pd

sample_sub = pd.read_csv("sample_submission.csv").set_index("index")
test = pd.read_csv("test.csv").set_index("index")
train = pd.read_csv("train.csv").set_index("index")

In [18]:
train.info()
train.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 751 entries, 0 to 750
Columns: 213 entries, IC50, mM to fr_urea
dtypes: float64(107), int64(106)
memory usage: 1.2 MB

,"IC50, mM","CC50, mM",SI,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
count,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,...,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.0,751.000000,751.000000,751.000000
mean,204.544021,577.426098,89.153313,10.860070,10.860070,0.180064,-0.971890,0.577938,29.588010,352.407345,...,0.055925,0.013316,0.010652,0.001332,0.001332,0.054594,0.0,0.069241,0.182423,0.006658
std,370.367937,641.515163,788.882198,3.347314,3.347314,0.169163,1.594491,0.214190,12.713195,129.071212,...,0.272400,0.114699,0.102728,0.036491,0.036491,0.227337,0.0,0.254033,1.227468,0.081377
min,0.003517,0.700808,0.011489,2.321942,2.321942,0.000039,-6.992796,0.059567,9.545455,110.156000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
25%,13.222351,99.998894,1.500000,8.921032,8.921032,0.048473,-1.333831,0.442842,18.306020,266.252000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
50%,44.069306,376.580899,4.000000,12.197500,12.197500,0.121372,-0.419485,0.636477,29.281250,319.129000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
75%,206.787402,877.508784,17.372463,13.214245,13.214245,0.290990,0.072488,0.742483,38.875000,410.537000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
max,4095.188563,4538.976189,15620.600000,15.933463,15.933463,1.374614,1.374614,0.947265,60.272727,904.777000,...,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,20.000000,1.000000

In [19]:
train.head()

,"IC50, mM","CC50, mM",SI,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
index,,,,,,,,,,,,,,,,,,,,,
0,102.414420,95.757483,0.935000,5.466584,5.466584,0.719259,0.719259,0.681165,18.307692,195.287,...,1,0,0,0,0,0,0,0,0,0
1,0.044333,8.401080,189.500000,11.492712,11.492712,0.012350,-3.798024,0.769122,27.652174,360.907,...,0,1,0,0,0,0,0,0,0,0
2,4.437964,50.085589,11.285714,5.366084,5.366084,0.522930,0.522930,0.612606,24.608696,315.457,...,0,0,0,0,0,0,0,0,0,0
3,6.827881,682.788051,100.000000,13.317130,13.317130,0.020658,-4.829339,0.345823,12.400000,439.375,...,0,0,1,0,0,0,0,0,0,0
4,2.003253,70.001455,34.943894,6.320833,6.320833,0.300347,0.300347,0.562066,60.272727,151.253,...,0,0,0,0,0,0,0,0,0,0